### ISSUE TITLE
是要本地打包  com.aliyun:numberauth 吗

### ISSUE THREAD

**Issue by virskor** [ningcol/atauth_flutter_plugin#1]
Could not determine the dependencies of task ':app:preDebugBuild'.      
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.aliyun:numberauth:2.10.1.

**Comment by ningcol** [comment]
不太了解你的意思

**Comment by CListery** [comment]
@virskor 由于阿里那边目前没有提供maven库版本的native sdk依赖方式，但是flutter目前只支持通过maven仓库方式的依赖，所以我们插件中android端的实现是基于 jforg私服 上传aliyun sdk再依赖的方式，所以插件中会报找不到 sdk 的情况
