### ISSUE TITLE
需要修改podfile来支持移动

### ISSUE THREAD

**Issue by virskor** [ningcol/atauth_flutter_plugin#2]
s.pod_target_xcconfig = { 'OTHER_LDFLAGS' => '-ObjC -all_load', 'DEFINES_MODULE' => 'YES', 'VALID_ARCHS[sdk=iphonesimulator*]' => 'x86_64' }

需要增加  'OTHER_LDFLAGS' => '-ObjC -all_load',

**Comment by CListery** [comment]
> s.pod_target_xcconfig = { 'OTHER_LDFLAGS' => '-ObjC -all_load', 'DEFINES_MODULE' => 'YES', 'VALID_ARCHS[sdk=iphonesimulator*]' => 'x86_64' }
> 
> 需要增加 'OTHER_LDFLAGS' => '-ObjC -all_load',

iOS目前可以直接跑起来，你是遇到什么问题？

**Comment by virskor** [comment]
@CListery IOS下移动会不生效，要手动在Pods 生成的atauth_flutter_plugin中添加OTHER LINK FLAGS -ObjC -all_load 才生效，电信联通则正常。安卓下正常

**Comment by CListery** [comment]
> @CListery IOS下移动会不生效，要手动在Pods 生成的atauth_flutter_plugin中添加OTHER LINK FLAGS -ObjC -all_load 才生效，电信联通则正常。安卓下正常

刚才回去查阅了下官方文档，确实是有这个问题，先没有理解你的意思，原来讲的是移动卡

**Comment by virskor** [comment]
是的，移动卡，我刚尝试
```
 s.pod_target_xcconfig = { 'OTHER_LDFLAGS' => '-ObjC -all_load', 'DEFINES_MODULE' => 'YES', 'VALID_ARCHS[sdk=iphonesimulator*]' => 'x86_64' }
```

后发现Xcode 根本没有自动明添加'OTHER_LDFLAGS' => '-ObjC -all_load' 这个就比较坑了，只能每次手动添加 flutter clean后又没有了。哈哈，有没有什么比较好的解决方案 @CListery

**Comment by CListery** [comment]
直接修改 atauth_flutter_plugin.podspec 添加

>  s.pod_target_xcconfig = { 'OTHER_LDFLAGS' => '-ObjC -all_load', 'DEFINES_MODULE' => 'YES', 'VALID_ARCHS[sdk=iphonesimulator*]' => 'x86_64' }

这一行应该可以在我们发布新版本前临时解决

**Comment by virskor** [comment]
好的
